#lang racket/base

(provide (all-defined-out))

(require ffi/unsafe ffi/unsafe/define syntax/parse/define)

(define-simple-macro (defines (name:id value:expr) ...)
  (begin (define name value) ...))

(defines
  (GLFW_TRUE                      1)
  (GLFW_FALSE                     0)
  (GLFW_RELEASE                   0)
  (GLFW_PRESS                     1)
  (GLFW_REPEAT                    2)
  (GLFW_KEY_UNKNOWN               -1)
  (GLFW_KEY_SPACE                 32)
  (GLFW_KEY_APOSTROPHE            39)
  (GLFW_KEY_COMMA                 44)
  (GLFW_KEY_MINUS                 45)
  (GLFW_KEY_PERIOD                46)
  (GLFW_KEY_SLASH                 47)
  (GLFW_KEY_0                     48)
  (GLFW_KEY_1                     49)
  (GLFW_KEY_2                     50)
  (GLFW_KEY_3                     51)
  (GLFW_KEY_4                     52)
  (GLFW_KEY_5                     53)
  (GLFW_KEY_6                     54)
  (GLFW_KEY_7                     55)
  (GLFW_KEY_8                     56)
  (GLFW_KEY_9                     57)
  (GLFW_KEY_SEMICOLON             59)
  (GLFW_KEY_EQUAL                 61)
  (GLFW_KEY_A                     65)
  (GLFW_KEY_B                     66)
  (GLFW_KEY_C                     67)
  (GLFW_KEY_D                     68)
  (GLFW_KEY_E                     69)
  (GLFW_KEY_F                     70)
  (GLFW_KEY_G                     71)
  (GLFW_KEY_H                     72)
  (GLFW_KEY_I                     73)
  (GLFW_KEY_J                     74)
  (GLFW_KEY_K                     75)
  (GLFW_KEY_L                     76)
  (GLFW_KEY_M                     77)
  (GLFW_KEY_N                     78)
  (GLFW_KEY_O                     79)
  (GLFW_KEY_P                     80)
  (GLFW_KEY_Q                     81)
  (GLFW_KEY_R                     82)
  (GLFW_KEY_S                     83)
  (GLFW_KEY_T                     84)
  (GLFW_KEY_U                     85)
  (GLFW_KEY_V                     86)
  (GLFW_KEY_W                     87)
  (GLFW_KEY_X                     88)
  (GLFW_KEY_Y                     89)
  (GLFW_KEY_Z                     90)
  (GLFW_KEY_LEFT_BRACKET          91)
  (GLFW_KEY_BACKSLASH             92)
  (GLFW_KEY_RIGHT_BRACKET         93)
  (GLFW_KEY_GRAVE_ACCENT          96)
  (GLFW_KEY_WORLD_1               161)
  (GLFW_KEY_WORLD_2               162)
  (GLFW_KEY_ESCAPE                256)
  (GLFW_KEY_ENTER                 257)
  (GLFW_KEY_TAB                   258)
  (GLFW_KEY_BACKSPACE             259)
  (GLFW_KEY_INSERT                260)
  (GLFW_KEY_DELETE                261)
  (GLFW_KEY_RIGHT                 262)
  (GLFW_KEY_LEFT                  263)
  (GLFW_KEY_DOWN                  264)
  (GLFW_KEY_UP                    265)
  (GLFW_KEY_PAGE_UP               266)
  (GLFW_KEY_PAGE_DOWN             267)
  (GLFW_KEY_HOME                  268)
  (GLFW_KEY_END                   269)
  (GLFW_KEY_CAPS_LOCK             280)
  (GLFW_KEY_SCROLL_LOCK           281)
  (GLFW_KEY_NUM_LOCK              282)
  (GLFW_KEY_PRINT_SCREEN          283)
  (GLFW_KEY_PAUSE                 284)
  (GLFW_KEY_F1                    290)
  (GLFW_KEY_F2                    291)
  (GLFW_KEY_F3                    292)
  (GLFW_KEY_F4                    293)
  (GLFW_KEY_F5                    294)
  (GLFW_KEY_F6                    295)
  (GLFW_KEY_F7                    296)
  (GLFW_KEY_F8                    297)
  (GLFW_KEY_F9                    298)
  (GLFW_KEY_F10                   299)
  (GLFW_KEY_F11                   300)
  (GLFW_KEY_F12                   301)
  (GLFW_KEY_F13                   302)
  (GLFW_KEY_F14                   303)
  (GLFW_KEY_F15                   304)
  (GLFW_KEY_F16                   305)
  (GLFW_KEY_F17                   306)
  (GLFW_KEY_F18                   307)
  (GLFW_KEY_F19                   308)
  (GLFW_KEY_F20                   309)
  (GLFW_KEY_F21                   310)
  (GLFW_KEY_F22                   311)
  (GLFW_KEY_F23                   312)
  (GLFW_KEY_F24                   313)
  (GLFW_KEY_F25                   314)
  (GLFW_KEY_KP_0                  320)
  (GLFW_KEY_KP_1                  321)
  (GLFW_KEY_KP_2                  322)
  (GLFW_KEY_KP_3                  323)
  (GLFW_KEY_KP_4                  324)
  (GLFW_KEY_KP_5                  325)
  (GLFW_KEY_KP_6                  326)
  (GLFW_KEY_KP_7                  327)
  (GLFW_KEY_KP_8                  328)
  (GLFW_KEY_KP_9                  329)
  (GLFW_KEY_KP_DECIMAL            330)
  (GLFW_KEY_KP_DIVIDE             331)
  (GLFW_KEY_KP_MULTIPLY           332)
  (GLFW_KEY_KP_SUBTRACT           333)
  (GLFW_KEY_KP_ADD                334)
  (GLFW_KEY_KP_ENTER              335)
  (GLFW_KEY_KP_EQUAL              336)
  (GLFW_KEY_LEFT_SHIFT            340)
  (GLFW_KEY_LEFT_CONTROL          341)
  (GLFW_KEY_LEFT_ALT              342)
  (GLFW_KEY_LEFT_SUPER            343)
  (GLFW_KEY_RIGHT_SHIFT           344)
  (GLFW_KEY_RIGHT_CONTROL         345)
  (GLFW_KEY_RIGHT_ALT             346)
  (GLFW_KEY_RIGHT_SUPER           347)
  (GLFW_KEY_MENU                  348)
  (GLFW_KEY_LAST                  GLFW_KEY_MENU)
  (GLFW_MOD_SHIFT                 #x0001)
  (GLFW_MOD_CONTROL               #x0002)
  (GLFW_MOD_ALT                   #x0004)
  (GLFW_MOD_SUPER                 #x0008)
  (GLFW_MOUSE_BUTTON_1            0)
  (GLFW_MOUSE_BUTTON_2            1)
  (GLFW_MOUSE_BUTTON_3            2)
  (GLFW_MOUSE_BUTTON_4            3)
  (GLFW_MOUSE_BUTTON_5            4)
  (GLFW_MOUSE_BUTTON_6            5)
  (GLFW_MOUSE_BUTTON_7            6)
  (GLFW_MOUSE_BUTTON_8            7)
  (GLFW_MOUSE_BUTTON_LAST         GLFW_MOUSE_BUTTON_8)
  (GLFW_MOUSE_BUTTON_LEFT         GLFW_MOUSE_BUTTON_1)
  (GLFW_MOUSE_BUTTON_RIGHT        GLFW_MOUSE_BUTTON_2)
  (GLFW_MOUSE_BUTTON_MIDDLE       GLFW_MOUSE_BUTTON_3)
  (GLFW_JOYSTICK_1                0)
  (GLFW_JOYSTICK_2                1)
  (GLFW_JOYSTICK_3                2)
  (GLFW_JOYSTICK_4                3)
  (GLFW_JOYSTICK_5                4)
  (GLFW_JOYSTICK_6                5)
  (GLFW_JOYSTICK_7                6)
  (GLFW_JOYSTICK_8                7)
  (GLFW_JOYSTICK_9                8)
  (GLFW_JOYSTICK_10               9)
  (GLFW_JOYSTICK_11               10)
  (GLFW_JOYSTICK_12               11)
  (GLFW_JOYSTICK_13               12)
  (GLFW_JOYSTICK_14               13)
  (GLFW_JOYSTICK_15               14)
  (GLFW_JOYSTICK_16               15)
  (GLFW_JOYSTICK_LAST             GLFW_JOYSTICK_16)
  (GLFW_NOT_INITIALIZED           #x00010001)
  (GLFW_NO_CURRENT_CONTEXT        #x00010002)
  (GLFW_INVALID_ENUM              #x00010003)
  (GLFW_INVALID_VALUE             #x00010004)
  (GLFW_OUT_OF_MEMORY             #x00010005)
  (GLFW_API_UNAVAILABLE           #x00010006)
  (GLFW_VERSION_UNAVAILABLE       #x00010007)
  (GLFW_PLATFORM_ERROR            #x00010008)
  (GLFW_FORMAT_UNAVAILABLE        #x00010009)
  (GLFW_NO_WINDOW_CONTEXT         #x0001000A)
  (GLFW_FOCUSED                   #x00020001)
  (GLFW_ICONIFIED                 #x00020002)
  (GLFW_RESIZABLE                 #x00020003)
  (GLFW_VISIBLE                   #x00020004)
  (GLFW_DECORATED                 #x00020005)
  (GLFW_AUTO_ICONIFY              #x00020006)
  (GLFW_FLOATING                  #x00020007)
  (GLFW_MAXIMIZED                 #x00020008)
  (GLFW_RED_BITS                  #x00021001)
  (GLFW_GREEN_BITS                #x00021002)
  (GLFW_BLUE_BITS                 #x00021003)
  (GLFW_ALPHA_BITS                #x00021004)
  (GLFW_DEPTH_BITS                #x00021005)
  (GLFW_STENCIL_BITS              #x00021006)
  (GLFW_ACCUM_RED_BITS            #x00021007)
  (GLFW_ACCUM_GREEN_BITS          #x00021008)
  (GLFW_ACCUM_BLUE_BITS           #x00021009)
  (GLFW_ACCUM_ALPHA_BITS          #x0002100A)
  (GLFW_AUX_BUFFERS               #x0002100B)
  (GLFW_STEREO                    #x0002100C)
  (GLFW_SAMPLES                   #x0002100D)
  (GLFW_SRGB_CAPABLE              #x0002100E)
  (GLFW_REFRESH_RATE              #x0002100F)
  (GLFW_DOUBLEBUFFER              #x00021010)
  (GLFW_CLIENT_API                #x00022001)
  (GLFW_CONTEXT_VERSION_MAJOR     #x00022002)
  (GLFW_CONTEXT_VERSION_MINOR     #x00022003)
  (GLFW_CONTEXT_REVISION          #x00022004)
  (GLFW_CONTEXT_ROBUSTNESS        #x00022005)
  (GLFW_OPENGL_FORWARD_COMPAT     #x00022006)
  (GLFW_OPENGL_DEBUG_CONTEXT      #x00022007)
  (GLFW_OPENGL_PROFILE            #x00022008)
  (GLFW_CONTEXT_RELEASE_BEHAVIOR  #x00022009)
  (GLFW_CONTEXT_NO_ERROR          #x0002200A)
  (GLFW_CONTEXT_CREATION_API      #x0002200B)
  (GLFW_NO_API                    0)
  (GLFW_OPENGL_API                #x00030001)
  (GLFW_OPENGL_ES_API             #x00030002)
  (GLFW_NO_ROBUSTNESS             0)
  (GLFW_NO_RESET_NOTIFICATION     #x00031001)
  (GLFW_LOSE_CONTEXT_ON_RESET     #x00031002)
  (GLFW_OPENGL_ANY_PROFILE        0)
  (GLFW_OPENGL_CORE_PROFILE       #x00032001)
  (GLFW_OPENGL_COMPAT_PROFILE     #x00032002)
  (GLFW_CURSOR                    #x00033001)
  (GLFW_STICKY_KEYS               #x00033002)
  (GLFW_STICKY_MOUSE_BUTTONS      #x00033003)
  (GLFW_CURSOR_NORMAL             #x00034001)
  (GLFW_CURSOR_HIDDEN             #x00034002)
  (GLFW_CURSOR_DISABLED           #x00034003)
  (GLFW_ANY_RELEASE_BEHAVIOR      0)
  (GLFW_RELEASE_BEHAVIOR_FLUSH    #x00035001)
  (GLFW_RELEASE_BEHAVIOR_NONE     #x00035002)
  (GLFW_NATIVE_CONTEXT_API        #x00036001)
  (GLFW_EGL_CONTEXT_API           #x00036002)
  (GLFW_ARROW_CURSOR              #x00036001)
  (GLFW_IBEAM_CURSOR              #x00036002)
  (GLFW_CROSSHAIR_CURSOR          #x00036003)
  (GLFW_HAND_CURSOR               #x00036004)
  (GLFW_HRESIZE_CURSOR            #x00036005)
  (GLFW_VRESIZE_CURSOR            #x00036006)
  (GLFW_CONNECTED                 #x00040001)
  (GLFW_DISCONNECTED              #x00040002)
  (GLFW_DONT_CARE                 -1)
  (GLFWglproc                     (_ptr o (_fun -> _void)))
  (GLFWvkproc                     (_ptr o (_fun -> _void)))
  (GLFWerrorfun                   (_ptr o (_fun _int _string/utf-8 -> _void)))
  (GLFWwindowposfun               (_ptr o (_fun _pointer _int _int -> _void)))
  (GLFWwindowsizefun              (_ptr o (_fun _pointer _int _int -> _void)))
  (GLFWwindowclosefun             (_ptr o (_fun _pointer -> _void)))
  (GLFWwindowrefreshfun           (_ptr o (_fun _pointer -> _void)))
  (GLFWwindowfocusfun             (_ptr o (_fun _pointer _int -> _void)))
  (GLFWwindowiconifyfun           (_ptr o (_fun _pointer _int -> _void)))
  (GLFWframebuffersizefun         (_ptr o (_fun _pointer _int _int -> _void)))
  (GLFWmousebuttonfun             (_ptr o (_fun _pointer _int _int _int -> _void)))
  (GLFWcursorposfun               (_ptr o (_fun _pointer _double _double -> _void)))
  (GLFWcursorenterfun             (_ptr o (_fun _pointer _int -> _void)))
  (GLFWscrollfun                  (_ptr o (_fun _pointer _double _double -> _void)))
  (GLFWkeyfun                     (_ptr o (_fun _pointer _int _int _int _int -> _void)))
  (GLFWcharfun                    (_ptr o (_fun _pointer _uint -> _void)))
  (GLFWcharmodsfun                (_ptr o (_fun _pointer _uint _int -> _void)))
  (GLFWdropfun                    (_ptr o (_fun _pointer _int (_ptr o _string/utf-8) -> _void)))
  (GLFWmonitorfun                 (_ptr o (_fun _pointer _int -> _void)))
  (GLFWjoystickfun                (_ptr o (_fun _int _int -> _void))))

(define-cstruct _GLFWvidmode
  ([width _int]
   [height _int]
   [redBits _int]
   [greenBits _int]
   [blueBits _int]
   [refreshRate _int]))

(define-cstruct _GLFWgammaramp
  ([red (_ptr o _ushort)]
   [green (_ptr o _ushort)]
   [blue (_ptr o _ushort)]
   [size _int]))

(define-cstruct _GLFWimage
  ([width _int]
   [height _int]
   [pixels (_ptr o _uint8)]))

(define-simple-macro (define-ffi-functions lib:expr (name:id (ctype:expr ...)) ...)
  (begin (define-ffi-definer lib-definer lib) (lib-definer name (_fun ctype ...)) ...))

(define-ffi-functions (ffi-lib "libglfw")
  (glfwInit                           (-> _int))
  (glfwTerminate                      (-> _void))
  (glfwGetVersion                     ((major : (_ptr o _int)) (minor : (_ptr o _int)) (rev : (_ptr o _int)) -> _void -> (values major minor rev)))
  (glfwGetVersionString               (-> _string/utf-8))
  (glfwSetErrorCallback               (GLFWerrorfun -> GLFWerrorfun))
  (glfwGetMonitors                    ((count : (_ptr o _int)) -> (_ptr o _pointer)))
  (glfwGetPrimaryMonitor              (-> _pointer))
  (glfwGetMonitorPos                  ((monitor : _pointer) (xpos : (_ptr o _int)) (ypos : (_ptr o _int)) -> _void -> (values xpos ypos)))
  (glfwGetMonitorPhysicalSize         ((monitor : _pointer) (widthMM : (_ptr o _int)) (heightMM : (_ptr o _int)) -> _void -> (values widthMM heightMM)))
  (glfwGetMonitorName                 ((monitor : _pointer) -> _string/utf-8))
  (glfwSetMonitorCallback             (GLFWmonitorfun -> GLFWmonitorfun))
  (glfwGetVideoModes                  ((monitor : _pointer) (count : (_ptr o _int)) -> (_ptr o _GLFWvidmode)))
  (glfwGetVideoMode                   ((monitor : _pointer) -> (_ptr o _GLFWvidmode)))
  (glfwSetGamma                       ((monitor : _pointer) (gamma : _float) -> _void))
  (glfwGetGammaRamp                   ((monitor : _pointer) -> (_ptr o _GLFWgammaramp)))
  (glfwSetGammaRamp                   ((monitor : _pointer) -> (_ptr o _GLFWgammaramp)))
  (glfwDefaultWindowHints             (-> _void))
  (glfwWindowHint                     ((hint : _int) (value : _int) -> _void))
  (glfwCreateWindow                   ((width : _int) (height : _int) (title : _string/utf-8) (monitor : _pointer) (share : _pointer) -> _pointer)) ; returns GLFWwindow *
  (glfwDestroyWindow                  ((window : _pointer) -> _void))
  (glfwWindowShouldClose              ((window : _pointer) -> _int))
  (glfwSetWindowShouldClose           ((window : _pointer) (value : _int) -> _void))
  (glfwSetWindowTitle                 ((window : _pointer) (title : _string/utf-8) -> _void))
  (glfwSetWindowIcon                  ((window : _pointer) (count : _int) (images : (_ptr o _GLFWimage)) -> _void))
  (glfwGetWindowPos                   ((window : _pointer) (xpos : (_ptr o _int)) (ypos : (_ptr o _int)) -> _void -> (values xpos ypos)))
  (glfwSetWindowPos                   ((window : _pointer) (xpos : _int) (ypos : _int) -> _void))
  (glfwGetWindowSize                  ((window : _pointer) (width : (_ptr o _int)) (height : (_ptr o _int)) -> _void -> (values width height)))
  (glfwSetWindowSizeLimits            ((window : _pointer) (minwidth : _int) (minheight : _int) (maxwidth : _int) (maxheight : _int) -> _void))
  (glfwSetWindowAspectRatio           ((window : _pointer) (numer : _int) (denom : _int) -> _void))
  (glfwSetWindowSize                  ((window : _pointer) (width : _int) (height : _int) -> _void))
  (glfwGetFramebufferSize             ((window : _pointer) (width : (_ptr o _int)) (height : (_ptr o _int)) -> _void -> (values width height)))
  (glfwGetWindowFrameSize             ((window : _pointer) (left : (_ptr o _int)) (top : (_ptr o _int)) (right : (_ptr o _int)) (bottom : (_ptr o _int)) -> _void -> (values left top right bottom)))
  (glfwIconifyWindow                  ((window : _pointer) -> _void))
  (glfwRestoreWindow                  ((window : _pointer) -> _void))
  (glfwMaximizeWindow                 ((window : _pointer) -> _void))
  (glfwShowWindow                     ((window : _pointer) -> _void))
  (glfwHideWindow                     ((window : _pointer) -> _void))
  (glfwFocusWindow                    ((window : _pointer) -> _void))
  (glfwGetWindowMonitor               ((window : _pointer) -> _pointer))
  (glfwSetWindowMonitor               ((window : _pointer) (monitor : _pointer) (xpos : _int) (ypos : _int) (width : _int) (height : _int) (refreshRate : _int) -> _void))
  (glfwGetWindowAttrib                ((window : _pointer) (attrib : _int) -> _int))
  (glfwSetWindowUserPointer           ((window : _pointer) (pointer : _pointer) -> _void))
  (glfwGetWindowUserPointer           ((window : _pointer) -> _pointer))
  (glfwSetWindowPosCallback           ((window : _pointer) GLFWwindowposfun -> GLFWwindowposfun))
  (glfwSetWindowSizeCallback          ((window : _pointer) GLFWwindowsizefun -> GLFWwindowsizefun))
  (glfwSetWindowCloseCallback         ((window : _pointer) GLFWwindowclosefun -> GLFWwindowclosefun))
  (glfwSetWindowRefreshCallback       ((window : _pointer) GLFWwindowrefreshfun -> GLFWwindowrefreshfun))
  (glfwSetWindowFocusCallback         ((window : _pointer) GLFWwindowfocusfun -> GLFWwindowfocusfun))
  (glfwSetWindowIconifyCallback       ((window : _pointer) GLFWwindowiconifyfun -> GLFWwindowiconifyfun))
  (glfwSetFramebufferSizeCallback     ((window : _pointer) GLFWframebuffersizefun -> GLFWframebuffersizefun))
  (glfwPollEvents                     (-> _void))
  (glfwWaitEvents                     (-> _void))
  (glfwWaitEventsTimeout              ((timeout : _double) -> _void))
  (glfwPostEmptyEvent                 (-> _void))
  (glfwGetInputMode                   ((window : _pointer) (mode : _int) -> _int))
  (glfwSetInputMode                   ((window : _pointer) (mode : _int) (value : _int) -> _void))
  (glfwGetKeyName                     ((key : _int) (scancode : _int) -> _string/utf-8))
  (glfwGetKey                         ((window : _pointer) (key : _int) -> _int))
  (glfwGetMouseButton                 ((window : _pointer) (button : _int) -> _int))
  (glfwGetCursorPos                   ((window : _pointer) (xpos : (_ptr o _double)) (ypos : (_ptr o _double)) -> _void -> (values xpos ypos)))
  (glfwSetCursorPos                   ((window : _pointer) (xpos : _double) (ypos : _double) -> _void))
  (glfwCreateCursor                   ((image : (_ptr o _GLFWimage)) (xhot : _int) (yhot : _int) -> _pointer))  ;; Return cursor ptr
  (glfwCreateStandardCursor           ((shape : _int) -> _pointer))  ;; Returns cursor ptr
  (glfwDestroyCursor                  ((cursor : _pointer) -> _void))
  (glfwSetCursor                      ((window : _pointer) (cursor : _pointer) -> _void))
  (glfwSetKeyCallback                 ((window : _pointer) GLFWkeyfun -> GLFWkeyfun))
  (glfwSetCharCallback                ((window : _pointer) GLFWcharfun -> GLFWcharfun))
  (glfwSetCharModsCallback            ((window : _pointer) GLFWcharmodsfun -> GLFWcharmodsfun))
  (glfwSetMouseButtonCallback         ((window : _pointer) GLFWmousebuttonfun -> GLFWmousebuttonfun));
  (glfwSetCursorPosCallback           ((window : _pointer) GLFWcursorposfun -> GLFWcursorposfun))
  (glfwSetCursorEnterCallback         ((window : _pointer) GLFWcursorenterfun -> GLFWcursorenterfun))
  (glfwSetScrollCallback              ((window : _pointer) GLFWscrollfun -> GLFWscrollfun))
  (glfwSetDropCallback                ((window : _pointer) GLFWdropfun -> GLFWdropfun));
  (glfwJoystickPresent                ((joy : _int) -> _int))
  (glfwGetJoystickAxes                ((joy : _int) (count : (_ptr o _int)) -> (_ptr o _float)))
  (glfwGetJoystickButtons             ((joy : _int) (count : (_ptr o _int)) -> (_ptr o _uint8)))  ; Returns const unsigned char*
  (glfwGetJoystickName                ((joy : _int) -> _string/utf-8))
  (glfwSetJoystickCallback            (GLFWjoystickfun -> GLFWjoystickfun))
  (glfwSetClipboardString             ((window : _pointer) (string : _string/utf-8) -> _void))
  (glfwGetClipboardString             ((window : _pointer) -> _string/utf-8))
  (glfwGetTime                        (-> _double))
  (glfwSetTime                        ((time : _double) -> _void))
  (glfwGetTimerValue                  (-> _uint64))
  (glfwGetTimerFrequency              (-> _uint64))
  (glfwMakeContextCurrent             ((window : _pointer) -> _void))
  (glfwGetCurrentContext              (-> _pointer)) ; returns GLFWwindow*
  (glfwSwapBuffers                    ((window : _pointer) -> _void))
  (glfwSwapInterval                   ((interval : _int) -> _void))
  (glfwExtensionSupported             ((extension : _string/utf-8) -> _int))
  (glfwGetProcAddress                 ((procname : _string/utf-8) -> GLFWglproc))
  (glfwVulkanSupported                (-> _int));
  (glfwGetRequiredInstanceExtensions  ((count : (_ptr o _uint32)) -> (_ptr o _string/utf-8)))

  ;; Not tested. Vulkan structs are unknown. May not match the implementation.
  (glfwGetInstanceProcAddress         ((instance : _pointer) (procname : _string/utf-8) -> GLFWvkproc))
  (glfwGetPhysicalDevicePresentationSupport ((instance : _pointer) (device : _pointer) (queuefamily : _uint32) -> _int))
  (glfwCreateWindowSurface            ((instance : _pointer) (window : _pointer) (allocator : _pointer) (surface : _pointer) -> _pointer)))
